### ISSUE TITLE
mac m1, clang: error: the clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by Inc0n** [dangduc/fzf-native#11]
I am on mac m1, installing this to try out to combine with fussy.

The prebuild binary is for x86_64, so I tried using the local build use-package snippet. 

The compilation halted with errors, the full log is attached below:
[fzf-native-module.error.log](https://github.com/dangduc/fzf-native/files/8971684/fzf-native-module.error.log)

**Comment by dangduc** [comment]
```
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
CMake Error at /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/Library/Developer/CommandLineTools/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/xception/.emacs.d/straight/build/fzf-native/build/CMakeFiles/CMakeTmp
```

I'm not especially familiar with clang build problems, but I think these lines in your build log [means](https://stackoverflow.com/questions/42864122/check-for-working-c-compiler-usr-bin-cc-broken ) there is a problem with your system's clang compiler (`cc`). You will have to fix `cc` first and then try building fzf-native again.

I haven't tried compile for M1, so there could be other problems once you get pass the issue with `cc`, though.

**Comment by dangduc** [comment]
You can try to remove the `march` compiler flag by setting the defcustom var before building,

```lisp
(setq fzf-native-module-cmake-args "-DCMAKE_C_FLAGS='-O3'")
```

**Comment by Inc0n** [comment]
Yeap, that has made it work and compiled.

Thanks!

**Comment by dangduc** [comment]
Now including Apple Silicon prebuild https://github.com/dangduc/fzf-native/blob/main/bin/Darwin/arm64/fzf-native-module.so
